### ISSUE TITLE
Occasional mkdir issues and native compatibility glitches

### ISSUE THREAD

**Issue by MSF-Jarvis** [MSF-Jarvis/AAC-Redux#1]
The script can't seem to be able to create directories outside of it's own folder, that's not much of an issue. But it also can't seem to connect to the basic shell command "source", giving [not found] errors.

**Comment by MSF-Jarvis** [comment]
We also need to specify the sizes for the popups - more work for me.

**Comment by faddat** [comment]
hmmmmmmm Okay.... so sadly, all of that is outside of my experience.  I can help somewhat with source:  Do we know if the commands are executed in a single "virtual terminal session?"  If not, then maybe it is working, and something else isn't being found....?

If they are not in the same session the env vars will not persist.  Probably best to set the env vars using a more traditional

export VARNAME=varval

**Comment by faddat** [comment]
This is my target:

An executable file that runs on WIndows, OSX, Linux with a double-click (using the magic of VirtualBox) presents the user with a set of options, and then craps out *only* a .zip file with the appropriate ROM.  

Also let's get @androgeek974 in here, too.  We are all working on this part time every set of eyes counts.  My team here in Ha Noi has had *INCREDIBLE* luck/progress with Golang (on unrelated projects).  Do you have any thoughts on Gophering?

**Comment by AndroGeek974** [comment]
I'm really interesting by your target @faddat and I think its possible to realize. For OSX and Linux we can use normal unix commands. For windows, as you say we can maybe use VirtualBox or maybe integrate cygwin can be a good idea.

Another idea : Web-AAC. I started to design a webpage (CSS) and searching a way to integrate linux commands in a web-app (ex: "mkdir -p Test" in webpage to create folder in local). I saw that PHP can do that, also we can use Python, Perl etc with the CGI method. I never use these methods but I really want to learn that.

Why I want a Web-AAC ? Simply because with webapps we can design our app as we want, it can be simpler to use, lighter and if it works well we can open a server to push Web-AAC on it then lambda-users will be able to build their ROM online and the files will be downloaded in local.

What do you think about it guys ?

**Comment by faddat** [comment]
I can provide the servers needed for web-aac.  And that is a damn fine
idea.

24GB/2x quad xeon sufficent?  I will tweak the compiler so it will make
each component only once in the cases where ROMs share components.

Hit me up on Skype or hangouts.  We have much work to do...

**Comment by faddat** [comment]
We will use docker containers to do the building.  It will make it much
easier overall.  No need to worry about CGI.  I bet I read the same page
you just did.... about 18 months ago when trying to do something similar.
The result was klouds.org.

**Comment by AndroGeek974** [comment]
Good to see that the project interest you, you can add me on hangouts with this mail : damienboyer97438@gmail.com
I'm really exciting to begin the work !

**Comment by MSF-Jarvis** [comment]
All this happened in only a day!!! I'm really interested by the possibility of a Web-AAC, but we REALLY need the Ubuntu version to work good before diverting attention to other possible Forks of this project. So, @faddat, since you say you're not much experienced with this, get started with the server side things and me @AndroGeek974 will concentrate on getting AAC-Redux up to the standards we want.

**Comment by AndroGeek974** [comment]
I can code the html5 part of Web-AAC but I need time, I have exams in two weeks, going to be hell for me. After that, I've holidays and will have all the time we want.
During my exams, If you guys have ideas of design and widgets management or anything else, please tell me. As you say @MSF-Jarvis, maybe you can begin the work on server and UNIX commands integration @faddat ?

We can use @MSF-Jarvis's AAC-Redux as base for Web-AAC. The major work is UNIX commands, I think.

Ideas for Web-AAC : 
- Loading bar during downloading sources
- Full ADB access to the device wich allow to display device infos to Web-AAC

**Comment by MSF-Jarvis** [comment]
That's really good of you, but please focus on your exams first. Parents can give you hell if you flunk an exam, trust me.

@faddat has already begun work and also arranged for a Nexus 5 to test the builds AAC does for us. Loading bar will be a bit of a headache but I think we can comeup with something but ADB seems next to impossible AFAIK.
